players:

  - name: black
    robot: False
    werewolf: True
    position:
        x: 1.01
        y: 0
        z: 0.47

  - name: red
    robot: True
    werewolf: False
    position:
        x: 0
        y: 0
        z: 0

  - name: white
    robot: False
    werewolf: False
    position:
        x: -1.25
        y: 0
        z: 0.7

  - name: blue
    robot: False
    werewolf: False
    position:
        x: -0.83
        y: 0
        z: 2.6

  - name: orange
    robot: False
    werewolf: False
    position:
        x: 0.45
        y: 0
        z: 2.67

  - name: pink
    robot: False
    werewolf: False
    position:
        x: -1.4
        y: 0
        z: 1.67

  - name: brown
    robot: False
    werewolf: False
    position:
        x: 1.17
        y: 0
        z: 1.90

file_storage:
  service_name: 'werewolf'
  host: '192.168.0.103'
  port: 139

logging:
  asr_path: 'C:\Users\kalins\Documents\Data\enterface_arc\asr'
  sensor_path: 'C:\Users\kalins\Documents\Data\enterface_arc\sensors'

messaging:

  #broker_host: "192.168.0.111"
  broker_host: "130.237.67.194"
  broker_port: 5672
  broker_user: "test"
  broker_pass: "test"

  # time server host
  time_server_host: "tcp://130.237.67.194:45321"

  # connection server
  connection_server_host: "tcp://130.237.67.194:45322"

  # sensor hosts
  mocap_host: "192.168.0.120"

  # exchanges
  artificial_agent: "artificial-agent"
  sensors: "sensors"
  pre_processing: "pre-processor"
  environment: "environment"
  wizard: "wizard"
  fatima: "fatima"

  # sensors
  microphone: "microphone"
  camera: "camera"
  kinect: "kinect"
  mocap: "mocap"
  tobii: "tobii"

  # new sensor
  new_sensor_mocap: "mocap.new_sensor.all"
  new_sensor_tobii: "tobii.new_sensor"

  # pre_processing
  mocap_processing: "mocap.processing"
  tobii_processing: "tobii.processing"
  openface: "openface"

  #processors
  mocaptobii_processing: "mocaptobii.processing"
  position_data: "position.data"
  asr_watson: "asr.data"
  dialogue_acts : "dialogue_act.data"
